---
- name: install cargo to compile rust-doh
  apt:
    name: cargo

- name: invoke cargo to get and compile rust-doh (may take a while...)
  command: cargo install doh-proxy
  args:
    creates: /root/.cargo/bin/doh-proxy
  notify: remove rust-doh compilation files

- name: copy rust-doh binary in place
  copy:
    src: /root/.cargo/bin/doh-proxy
    dest: "{{ srv_doh_binary }}"
    remote_src: true
    mode: 0755
  notify: remove rust-doh compilation files
...
