---
- block:
    # this block installs rust-doh from zip
    # and strips top archive directory (unzip cannot do that)

    - name: install rust-doh from zip archive (preferred)
      unarchive:
        remote_src: true
        src: "{{ srv_doh_zip_url }}"
        dest: /tmp
        exclude: README.md

    - name: move rust-doh binary in place
      command: mv /tmp/doh-proxy-linux-x86_64/doh-proxy "{{ srv_doh_binary }}"
      args:
        creates: "{{ srv_doh_binary }}"

    - name: ensure rust-doh binary is executable
      file:
        path: "{{ srv_doh_binary }}"
        state: file
        owner: root
        group: root
        mode: 0755

    - name: remove temporary directory after unzipping rust-doh
      file:
        path: /tmp/doh-proxy-linux-x86_64
        state: absent
  when: srv_doh_zip_url |default('')


- name: install rust-doh from package (not recommended)
  apt:
    deb: "{{ srv_doh_deb_url }}"
    # workaround for libc6 and libgcc1 dependency problems on xenial
    # warning: apt remembers broken dependencies in package cache
    #          making other apt installs fail, please avoid!
    force: true
  when:
    - srv_doh_zip_url == ''  # noqa 602
    - srv_doh_deb_url != ''  # noqa 602


- name: compile and install rust-doh binary (very long)
  # warning: rust compilation takes 20+ minutes!
  import_tasks: compile.yml
  when:
    - srv_doh_zip_url == ''  # noqa 602
    - srv_doh_deb_url == ''  # noqa 602
...
