---
# handlers file for ivansible.srv_doh

- name: restart rust-doh service
  systemd:
    name: rust-doh
    state: restarted
    daemon_reload: yes
  become: yes

- name: remove rust-doh compilation files
  file:
    path: /root/.cargo
    state: absent
  become: yes
...
